version: "3.8"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    expose:
      - "8888"
    depends_on:
      - mariadb
    networks:
      - flask_network

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "8888:80"
      - "8000:8000"  # Mở port Flask ra ngoài luôn
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask
      - mariadb
    networks:
      - flask_network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-dev
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: flask_cms
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge

volumes:
  mariadb_data:
