"""Initial migration.

Revision ID: 4abb8c9eac2c
Revises: 
Create Date: 2025-04-17 00:29:29.176654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abb8c9eac2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('option_key', sa.String(length=255), nullable=False),
    sa.Column('option_value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_key')
    )
    op.create_table('terms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISH', 'DRAFT', 'PENDING', 'PRIVATE', 'TRASH', name='poststatus'), nullable=False),
    sa.Column('type', sa.Enum('POST', 'PAGE', 'ATTACHMENT', name='posttype'), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('term_taxonomy',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('taxonomy', sa.Enum('terms', 'tag', 'product_cat', 'product_tag', 'product_brand'), nullable=False),
    sa.Column('parent', sa.BigInteger(), nullable=True),
    sa.Column('count', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parent'], ['term_taxonomy.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_meta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('meta_key', sa.String(length=255), nullable=False),
    sa.Column('meta_value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_key'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'meta_key', name='uq_user_meta')
    )
    op.create_table('post_meta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('meta_key', sa.String(length=255), nullable=False),
    sa.Column('meta_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_term_relationships',
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('term_taxonomy_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_taxonomy_id'], ['term_taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('object_id', 'term_taxonomy_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_term_relationships')
    op.drop_table('post_meta')
    op.drop_table('user_meta')
    op.drop_table('term_taxonomy')
    op.drop_table('posts')
    op.drop_table('customers')
    op.drop_table('terms')
    op.drop_table('options')
    # ### end Alembic commands ###
